const myArray : string[] = ['hi', 'sd'];
const myArrayToo: Array<number> = [2,3,4,1];
const myString : string = 'supermain';
const myNumber : number = 99;
const myBoolean : boolean = true;
console.log(typeof myArray);
console.log(typeof myString);
console.log(typeof myNumber);
console.log(typeof myBoolean);
console.log(myArrayToo);
